[phases.build]
cmds = [
  "npm ci --omit=dev --ignore-scripts",
  "chmod +x deploy.sh",
  "./deploy.sh"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"